version: "3.3"
services:
  postgres:
    image:  postgres:alpine
    environment:
       POSTGRES_PASSWORD: example
  django:
    image: django
    build:
      context: ./django
      dockerfile: docker/Dockerfile
    volumes:
      - './django:/django'
    depends_on:
      - postgres
